'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Blender_Addon_Creator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to asss.
        '''</summary>
        Friend ReadOnly Property asse() As String
            Get
                Return ResourceManager.GetString("asse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to row = layout.row()
        '''row.operator(&quot;mesh.primitive_cube_add&quot;, text=&quot;hey man&quot;, icon=&quot;BLENDER&quot;).
        '''</summary>
        Friend ReadOnly Property button() As String
            Get
                Return ResourceManager.GetString("button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to row.operator(&quot;render.render&quot;)
        '''sub = row.row()
        '''sub.operator(&quot;render.render&quot;)
        '''row.operator(&quot;render.render&quot;).
        '''</summary>
        Friend ReadOnly Property buttonrows() As String
            Get
                Return ResourceManager.GetString("buttonrows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to # Create two columns, by using a split layout.
        '''        split = layout.split()
        '''
        '''        # First column
        '''        col = split.column()
        '''        col.label(text=&quot;Column One:&quot;)
        '''        col.prop(scene, &quot;frame_end&quot;)
        '''        col.prop(scene, &quot;frame_start&quot;)
        '''
        '''        # Second column, aligned
        '''        col = split.column(align=True)
        '''        col.label(text=&quot;Column Two:&quot;)
        '''        col.prop(scene, &quot;frame_start&quot;)
        '''        col.prop(scene, &quot;frame_end&quot;).
        '''</summary>
        Friend ReadOnly Property columns() As String
            Get
                Return ResourceManager.GetString("columns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;&apos;&apos;
        '''Copyright (C) CURRENT_YEAR YOUR NAME
        '''YOUR@MAIL.com
        '''
        '''Created by YOUR NAME
        '''
        '''    This program is free software: you can redistribute it and/or modify
        '''    it under the terms of the GNU General Public License as published by
        '''    the Free Software Foundation, either version 3 of the License, or
        '''    (at your option) any later version.
        '''
        '''    This program is distributed in the hope that it will be useful,
        '''    but WITHOUT ANY WARRANTY; without even the implied warranty of
        '''    MERCHANTABILITY or FITNES [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property gpl() As String
            Get
                Return ResourceManager.GetString("gpl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  row = layout.row()
        ''' row.label(text=&quot;Hello world!&quot;, icon=&apos;WORLD_DATA&apos;).
        '''</summary>
        Friend ReadOnly Property header() As String
            Get
                Return ResourceManager.GetString("header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to bl_info = {
        '''    &quot;name&quot;: &quot;Your Addon Name&quot;,
        '''    &quot;description&quot;: &quot;&quot;,
        '''    &quot;author&quot;: &quot;Your Name&quot;,
        '''    &quot;version&quot;: (0, 0, 1),
        '''    &quot;blender&quot;: BLENDER_VERSION,
        '''    &quot;location&quot;: &quot;View3D&quot;,
        '''    &quot;warning&quot;: &quot;This addon is still in development.&quot;,
        '''    &quot;wiki_url&quot;: &quot;&quot;,
        '''    &quot;category&quot;: &quot;Object&quot; }.
        '''</summary>
        Friend ReadOnly Property info() As String
            Get
                Return ResourceManager.GetString("info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to row = layout.row()
        '''row.prop(obj, &quot;name&quot;).
        '''</summary>
        Friend ReadOnly Property inputbox() As String
            Get
                Return ResourceManager.GetString("inputbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to if __name__ == &quot;__main__&quot;:
        '''    register().
        '''</summary>
        Friend ReadOnly Property mk() As String
            Get
                Return ResourceManager.GetString("mk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to class runthis(bpy.types.Operator):
        '''    bl_idname = &quot;your.operator&quot;
        '''    bl_label = &quot;your function&quot;
        '''    bl_description = &quot;what it will do&quot;
        '''    bl_options = {&quot;REGISTER&quot;}
        '''
        '''    @classmethod
        '''    def poll(cls, context):
        '''       return True
        '''
        '''    def execute(self, context):
        '''       return {&quot;FINISHED&quot;}.
        '''</summary>
        Friend ReadOnly Property opera() As String
            Get
                Return ResourceManager.GetString("opera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''class HelloWorldPanel(bpy.types.Panel):
        '''    &quot;&quot;&quot;Creates a Panel in the Object properties window&quot;&quot;&quot;
        '''    bl_label = &quot;Hello World Panel&quot;
        '''    bl_idname = &quot;OBJECT_PT_hello&quot;
        '''    bl_space_type = &apos;PROPERTIES&apos;
        '''    bl_region_type = &apos;WINDOW&apos;
        '''    bl_context = &quot;object&quot;
        '''
        '''    def draw(self, context):
        '''        layout = self.layout
        '''
        '''        obj = context.object.
        '''</summary>
        Friend ReadOnly Property pan() As String
            Get
                Return ResourceManager.GetString("pan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to class LayoutDemoPanel(bpy.types.Panel):
        '''    &quot;&quot;&quot;Creates a Panel in the scene context of the properties editor&quot;&quot;&quot;
        '''    bl_label = &quot;Layout Demo&quot;
        '''    bl_idname = &quot;SCENE_PT_layout&quot;
        '''    bl_space_type = &apos;PROPERTIES&apos;
        '''    bl_region_type = &apos;WINDOW&apos;
        '''    bl_context = &quot;scene&quot;
        '''
        '''    def draw(self, context):
        '''        layout = self.layout
        '''
        '''        scene = context.scene.
        '''</summary>
        Friend ReadOnly Property paneldrop() As String
            Get
                Return ResourceManager.GetString("paneldrop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to class LayoutDemoPanel(bpy.types.Panel):
        '''    &quot;&quot;&quot;Creates a Panel in the material context of the properties editor&quot;&quot;&quot;
        '''    bl_label = &quot;Layout Demo&quot;
        '''    bl_idname = &quot;MAT_PT_layout&quot;
        '''    bl_space_type = &apos;PROPERTIES&apos;
        '''    bl_region_type = &apos;WINDOW&apos;
        '''    bl_context = &quot;material&quot;
        '''
        '''    def draw(self, context):
        '''        layout = self.layout
        '''
        '''        scene = context.scene.
        '''</summary>
        Friend ReadOnly Property pm() As String
            Get
                Return ResourceManager.GetString("pm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to class LayoutDemoPanel(bpy.types.Panel):
        '''    &quot;&quot;&quot;Creates a Panel in the object context of the properties editor&quot;&quot;&quot;
        '''    bl_label = &quot;Layout Demo&quot;
        '''    bl_idname = &quot;OBJ_PT_layout&quot;
        '''    bl_space_type = &apos;PROPERTIES&apos;
        '''    bl_region_type = &apos;WINDOW&apos;
        '''    bl_context = &quot;object&quot;
        '''
        '''    def draw(self, context):
        '''        layout = self.layout
        '''
        '''        scene = context.scene.
        '''</summary>
        Friend ReadOnly Property po() As String
            Get
                Return ResourceManager.GetString("po", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to class LayoutDemoPanel(bpy.types.Panel):
        '''    &quot;&quot;&quot;Creates a Panel in the render context of the properties editor&quot;&quot;&quot;
        '''    bl_label = &quot;Layout Demo&quot;
        '''    bl_idname = &quot;RENDER_PT_layout&quot;
        '''    bl_space_type = &apos;PROPERTIES&apos;
        '''    bl_region_type = &apos;WINDOW&apos;
        '''    bl_context = &quot;render&quot;
        '''
        '''    def draw(self, context):
        '''        layout = self.layout
        '''
        '''        scene = context.scene.
        '''</summary>
        Friend ReadOnly Property pr() As String
            Get
                Return ResourceManager.GetString("pr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to class LayoutDemoPanel(bpy.types.Panel):
        '''    &quot;&quot;&quot;Creates a Panel in the render layer context of the properties editor&quot;&quot;&quot;
        '''    bl_label = &quot;Layout Demo&quot;
        '''    bl_idname = &quot;REL_PT_layout&quot;
        '''    bl_space_type = &apos;PROPERTIES&apos;
        '''    bl_region_type = &apos;WINDOW&apos;
        '''    bl_context = &quot;render_layer&quot;
        '''
        '''    def draw(self, context):
        '''        layout = self.layout
        '''
        '''        scene = context.scene.
        '''</summary>
        Friend ReadOnly Property prl() As String
            Get
                Return ResourceManager.GetString("prl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to class LayoutDemoPanel(bpy.types.Panel):
        '''    &quot;&quot;&quot;Creates a Panel in the scene context of the properties editor&quot;&quot;&quot;
        '''    bl_label = &quot;Layout Demo&quot;
        '''    bl_idname = &quot;SCENE_PT_layout&quot;
        '''    bl_space_type = &apos;PROPERTIES&apos;
        '''    bl_region_type = &apos;WINDOW&apos;
        '''    bl_context = &quot;scene&quot;
        '''
        '''    def draw(self, context):
        '''        layout = self.layout
        '''
        '''        scene = context.scene.
        '''</summary>
        Friend ReadOnly Property ps() As String
            Get
                Return ResourceManager.GetString("ps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to class LayoutDemoPanel(bpy.types.Panel):
        '''    &quot;&quot;&quot;Creates a Panel in the tools of the 3d view&quot;&quot;&quot;
        '''    bl_label = &quot;Layout Demo&quot;
        '''    bl_idname = &quot;TOOLS_PT_layout&quot;
        '''    bl_space_type = &apos;VIEW_3D&apos;
        '''    bl_region_type = &apos;UI&apos;
        '''    bl_context = &quot;&quot;
        '''
        '''    def draw(self, context):
        '''        layout = self.layout
        '''
        '''        scene = context.scene.
        '''</summary>
        Friend ReadOnly Property pt() As String
            Get
                Return ResourceManager.GetString("pt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to class LayoutDemoPanel(bpy.types.Panel):
        '''    &quot;&quot;&quot;Creates a Panel in the world context of the properties editor&quot;&quot;&quot;
        '''    bl_label = &quot;Layout Demo&quot;
        '''    bl_idname = &quot;WOD_PT_layout&quot;
        '''    bl_space_type = &apos;PROPERTIES&apos;
        '''    bl_region_type = &apos;WINDOW&apos;
        '''    bl_context = &quot;world&quot;
        '''
        '''    def draw(self, context):
        '''        layout = self.layout
        '''
        '''        scene = context.scene.
        '''</summary>
        Friend ReadOnly Property pw() As String
            Get
                Return ResourceManager.GetString("pw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to row = layout.row()
        '''row.prop(scene, &quot;frame_start&quot;).
        '''</summary>
        Friend ReadOnly Property range() As String
            Get
                Return ResourceManager.GetString("range", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to def register():
        '''    bpy.utils.register_class(__name__)
        '''
        '''def unregister():
        '''    bpy.utils.unregister_class(__name__)
        '''
        '''if __name__ == &quot;__main__&quot;:
        '''    register().
        '''</summary>
        Friend ReadOnly Property regunreg() As String
            Get
                Return ResourceManager.GetString("regunreg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to class HelloWorldTabPanel(bpy.types.Panel):
        '''    &quot;&quot;&quot;Creates a Panel in the Object properties window&quot;&quot;&quot;
        '''    bl_label = &quot;Hello World Panel&quot;
        '''    bl_space_type = &apos;VIEW_3D&apos;
        '''    bl_region_type = &apos;TOOLS&apos;
        '''    bl_context = &quot;object&quot;
        '''    bl_category = &apos;My Addon&apos;
        '''
        '''    def draw(self, context):
        '''        layout = self.layout
        '''
        '''        obj = context.object.
        '''</summary>
        Friend ReadOnly Property tab() As String
            Get
                Return ResourceManager.GetString("tab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to layout.label(text=&quot; Simple Row:&quot;).
        '''</summary>
        Friend ReadOnly Property text() As String
            Get
                Return ResourceManager.GetString("text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to create_world_nodes().
        '''</summary>
        Friend ReadOnly Property WORLD() As String
            Get
                Return ResourceManager.GetString("WORLD", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
